site_name: 'Jobeet'
site_description: 'Symfony 4.1 Jobeet Tutorial'
site_author: 'Gregurco Vlad'
repo_url: 'https://github.com/gregurco/jobeet-tutorial'
repo_name: 'GitHub'
edit_uri: blob/master/
docs_dir: ''
theme: readthedocs
pages:
  - Home: README.md
